### ISSUE TITLE
iPhone Support

### ISSUE THREAD

**Issue by seanoshea** [gffny/rgbycch#2]
Should this be left as an iPad only project?

**Comment by gffny** [comment]
I believe this incarnation should be iPad only. I envision an iPhone or other smart device app for players to initially sign into practices (bluetooth handshake with coach application on iPad), and at a later date to  look at their incidents, respond to requests for practice/match availability

**Comment by seanoshea** [comment]
iPad only it is!

**Comment by seanoshea** [comment]
Something to consider all the same: https://twitter.com/WaltBTIG/status/623611428751151104

**Comment by gffny** [comment]
I can see that we'll probably move towards more devices as screen real-estate becomes more available. I logically see a differential between a coach and player app, at the moment that's manifested in iPad vs iPhone.
