### ISSUE TITLE
CI Flow

### ISSUE THREAD

**Issue by seanoshea** [gffny/rgbycch#4]
Should fully build the iOS app and the server. Run the unit tests and coverage too.

**Comment by gffny** [comment]
I can create an account on travis-ci

**Comment by seanoshea** [comment]
Yep - definitely worthwhile to log into travis with your github credentials. Lets see if https://travis-ci.org/seanoshea/rgbycch/builds/71996165 gets its act together and actually builds before enabling travis for the master repo.

**Comment by gffny** [comment]
I think Travis is looking for a pom file in the root directory otherwise it fails over to Ant

**Comment by gffny** [comment]
I just added a dummy ant build file to pass Travis CI build. It appears to be working now if you want to do a pull @seanoshea

**Comment by seanoshea** [comment]
Hmmm. I dunno if this is gonna work without splitting the project up a little. See https://github.com/gffny/rgbycch/pull/10 for a suggestion.

**Comment by seanoshea** [comment]
See https://github.com/gffny/rgbycch/issues/9. Need to get that sorted before any CI work can continue.
